# version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    hostname: localhost
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travelokaclone
    ports:
      - "5432:5432"

  auth-service:
    build:
      context: ./auth-service
    depends_on:
      - db
    environment:
      DSN: "host=db user=postgres password=postgres dbname=travelokaclone port=5432 sslmode=disable"
    ports:
      - "8080:8080"

  booking-service:
    build:
      context: ./booking-service
    depends_on:
      - db
    environment:
      DSN: "host=db user=postgres password=postgres dbname=travelokaclone port=5432 sslmode=disable"
    ports:
      - "8081:8080"

  payment-service:
    build:
      context: ./payment-service
    depends_on:
      - db
    environment:
      DSN: "host=db user=postgres password=postgres dbname=travelokaclone port=5432 sslmode=disable"
    ports:
      - "8082:8080"

  admin-service:
    build:
      context: ./admin-service
    depends_on:
      - db
    environment:
      DSN: "host=db user=postgres password=postgres dbname=travelokaclone port=5432 sslmode=disable"
    ports:
      - "8084:8080"